#!/usr/bin/env bash
# Install nginx on web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with
# GET request (requesting a page) using
# curl, it must return a page that
# contains the string Hello World!

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i 's/80 default_server/80/g' /etc/nginx/sites-available/default
sudo service nginx start
echo 'Hello World!' | sudo tee /var/www/html/index.html

