#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get install -y software-properties-common
add-apt-respository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web-01 and web02
echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 172282-web-01 100.26.153.75:80 check
    server 172282-web-02 100.25.135.170:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
