#!/bin/bash

# Set variables for server IP address and private key location
SERVER_IP="54.237.89.28"
PRIVATE_KEY=~/.ssh/school

# Use ssh to connect to server with specified private key and user
ssh -i $PRIVATE_KEY ubuntu@$SERVER_IP

